"use client"

import type React from "react"
import { useState, useEffect } from "react"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { allSkills } from "@/lib/mock-data"
import { Calendar, CheckCircle2, Video, Copy, Check } from "lucide-react"
import { generateGoogleMeetLink, isValidGoogleMeetLink } from "@/lib/google-meet"

interface ScheduleSessionDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function ScheduleSessionDialog({ open, onOpenChange }: ScheduleSessionDialogProps) {
  const [step, setStep] = useState(1)
  const [skill, setSkill] = useState("")
  const [sessionType, setSessionType] = useState<"online" | "offline">("online")
  const [date, setDate] = useState("")
  const [time, setTime] = useState("")
  const [location, setLocation] = useState("")
  const [meetingLink, setMeetingLink] = useState("")
  const [autoGeneratedLink, setAutoGeneratedLink] = useState("")
  const [copied, setCopied] = useState(false)
  const [useCustomLink, setUseCustomLink] = useState(false)
  const [linkError, setLinkError] = useState("")

  // Auto-generate Google Meet link when skill or session type changes (only if not using custom link)
  useEffect(() => {
    if (sessionType === "online" && skill) {
      const generatedLink = generateGoogleMeetLink(skill)
      setAutoGeneratedLink(generatedLink)
      // Only set auto-generated link if user hasn't chosen to use custom link
      if (!useCustomLink && (!meetingLink || meetingLink === autoGeneratedLink)) {
        setMeetingLink(generatedLink)
      }
    } else {
      setAutoGeneratedLink("")
      if (sessionType === "offline") {
        setMeetingLink("")
        setUseCustomLink(false)
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [skill, sessionType])

  // Validate Google Meet link
  const validateMeetLink = (link: string) => {
    if (!link) {
      setLinkError("")
      return true
    }
    if (!isValidGoogleMeetLink(link)) {
      setLinkError("Please enter a valid Google Meet link (e.g., https://meet.google.com/abc-defg-hij)")
      return false
    }
    setLinkError("")
    return true
  }

  const handleMeetingLinkChange = (value: string) => {
    setMeetingLink(value)
    if (value) {
      setUseCustomLink(true)
      validateMeetLink(value)
    } else {
      setUseCustomLink(false)
      setLinkError("")
    }
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    
    // Validate meeting link if online session
    if (sessionType === "online" && meetingLink) {
      if (!validateMeetLink(meetingLink)) {
        return // Don't submit if link is invalid
      }
    }
    
    // In a real app, would create session
    console.log("Scheduling session:", { skill, sessionType, date, time, location, meetingLink })
    setStep(3)
  }

  const handleClose = () => {
    setStep(1)
    setSkill("")
    setSessionType("online")
    setDate("")
    setTime("")
    setLocation("")
    setMeetingLink("")
    setAutoGeneratedLink("")
    setUseCustomLink(false)
    setLinkError("")
    setCopied(false)
    onOpenChange(false)
  }

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-lg">
        {step === 1 && (
          <>
            <DialogHeader>
              <DialogTitle>Schedule a Session</DialogTitle>
              <DialogDescription>Choose a skill you want to teach or learn</DialogDescription>
            </DialogHeader>

            <form
              onSubmit={(e) => {
                e.preventDefault()
                setStep(2)
              }}
              className="space-y-4"
            >
              <div className="space-y-2">
                <Label htmlFor="session-skill">Select Skill</Label>
                <Input
                  id="session-skill"
                  placeholder="e.g., React Development"
                  value={skill}
                  onChange={(e) => setSkill(e.target.value)}
                  list="skills-list"
                  required
                />
                <datalist id="skills-list">
                  {allSkills.map((s) => (
                    <option key={s} value={s} />
                  ))}
                </datalist>
                <p className="text-xs text-muted-foreground">Choose from your skills or browse matches</p>
              </div>

              <div className="space-y-3">
                <Label>Session Type</Label>
                <RadioGroup value={sessionType} onValueChange={(v) => setSessionType(v as "online" | "offline")}>
                  <div className="flex items-center space-x-2 rounded-lg border border-border p-4 cursor-pointer hover:bg-accent/5">
                    <RadioGroupItem value="online" id="online" />
                    <Label htmlFor="online" className="flex-1 cursor-pointer">
                      <div className="font-medium">Online Session</div>
                      <div className="text-xs text-muted-foreground">Meet via video call</div>
                    </Label>
                  </div>
                  <div className="flex items-center space-x-2 rounded-lg border border-border p-4 cursor-pointer hover:bg-accent/5">
                    <RadioGroupItem value="offline" id="offline" />
                    <Label htmlFor="offline" className="flex-1 cursor-pointer">
                      <div className="font-medium">In-Person Session</div>
                      <div className="text-xs text-muted-foreground">Meet at a physical location</div>
                    </Label>
                  </div>
                </RadioGroup>
              </div>

              <div className="flex gap-2 justify-end">
                <Button type="button" variant="outline" onClick={handleClose}>
                  Cancel
                </Button>
                <Button type="submit">Continue</Button>
              </div>
            </form>
          </>
        )}

        {step === 2 && (
          <>
            <DialogHeader>
              <DialogTitle>Schedule Details</DialogTitle>
              <DialogDescription>Choose date, time, and location for your session</DialogDescription>
            </DialogHeader>

            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="session-date">Date</Label>
                  <Input
                    id="session-date"
                    type="date"
                    value={date}
                    onChange={(e) => setDate(e.target.value)}
                    required
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="session-time">Time</Label>
                  <Input
                    id="session-time"
                    type="time"
                    value={time}
                    onChange={(e) => setTime(e.target.value)}
                    required
                  />
                </div>
              </div>

              {sessionType === "offline" && (
                <div className="space-y-2">
                  <Label htmlFor="session-location">Location</Label>
                  <Input
                    id="session-location"
                    placeholder="e.g., Campus Library, Room 204"
                    value={location}
                    onChange={(e) => setLocation(e.target.value)}
                    required={sessionType === "offline"}
                  />
                </div>
              )}

              {sessionType === "online" && (
                <div className="space-y-3">
                <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <Label htmlFor="meeting-link">Google Meet Link</Label>
                      <span className="text-xs text-muted-foreground">Paste your meeting link here</span>
                    </div>
                    <div className="flex items-center gap-2">
                  <Input
                    id="meeting-link"
                        placeholder="https://meet.google.com/abc-defg-hij"
                    value={meetingLink}
                        onChange={(e) => handleMeetingLinkChange(e.target.value)}
                        onPaste={(e) => {
                          const pastedText = e.clipboardData.getData('text')
                          handleMeetingLinkChange(pastedText)
                        }}
                        className={`font-mono text-sm ${linkError ? 'border-red-500' : ''}`}
                        required={sessionType === "online"}
                      />
                      {meetingLink && (
                        <Button
                          type="button"
                          variant="outline"
                          size="icon"
                          onClick={() => {
                            navigator.clipboard.writeText(meetingLink)
                            setCopied(true)
                            setTimeout(() => setCopied(false), 2000)
                          }}
                        >
                          {copied ? (
                            <Check className="h-4 w-4 text-green-500" />
                          ) : (
                            <Copy className="h-4 w-4" />
                          )}
                        </Button>
                      )}
                    </div>
                    {linkError && (
                      <p className="text-xs text-red-500">{linkError}</p>
                    )}
                    {autoGeneratedLink && !useCustomLink && (
                      <div className="flex items-center gap-2 p-3 rounded-md bg-accent/10 border border-accent/20">
                        <Video className="h-4 w-4 text-primary" />
                        <div className="flex-1">
                          <p className="text-xs font-medium text-muted-foreground mb-1">
                            Auto-generated link available
                          </p>
                          <p className="text-xs text-muted-foreground">
                            You can paste your own Google Meet link above, or use the generated one
                          </p>
                        </div>
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          className="h-7 text-xs"
                          onClick={() => {
                            setMeetingLink(autoGeneratedLink)
                            setUseCustomLink(false)
                            setLinkError("")
                          }}
                        >
                          Use Generated
                        </Button>
                      </div>
                    )}
                    {useCustomLink && !linkError && meetingLink && (
                      <div className="flex items-center gap-2 p-2 rounded-md bg-green-50 dark:bg-green-950/20 border border-green-200 dark:border-green-800">
                        <Check className="h-4 w-4 text-green-500" />
                        <p className="text-xs text-green-700 dark:text-green-400">
                          Your Google Meet link is ready
                        </p>
                      </div>
                    )}
                    <div className="bg-blue-50 dark:bg-blue-950/20 rounded-lg p-3 text-xs border border-blue-200 dark:border-blue-800">
                      <p className="font-medium text-blue-900 dark:text-blue-300 mb-1">
                        💡 For Mentors Teaching Skills:
                      </p>
                      <p className="text-blue-700 dark:text-blue-400 leading-relaxed">
                        Paste your Google Meet link here. This link will be shared with students who book sessions with you. 
                        You can create a meeting in Google Calendar or use an existing meeting link.
                      </p>
                    </div>
                  </div>
                </div>
              )}

              <div className="flex gap-2 justify-end">
                <Button type="button" variant="outline" onClick={() => setStep(1)}>
                  Back
                </Button>
                <Button type="submit">
                  <Calendar className="mr-2 h-4 w-4" />
                  Schedule Session
                </Button>
              </div>
            </form>
          </>
        )}

        {step === 3 && (
          <div className="py-6 text-center">
            <div className="flex justify-center mb-4">
              <div className="flex h-16 w-16 items-center justify-center rounded-full bg-accent text-accent-foreground">
                <CheckCircle2 className="h-8 w-8" />
              </div>
            </div>
            <h3 className="text-xl font-semibold mb-2">Session Scheduled!</h3>
            <p className="text-sm text-muted-foreground mb-4 text-pretty leading-relaxed">
              Your {skill} session has been scheduled for {new Date(date).toLocaleDateString()} at {time}.
              {sessionType === "online" ? " Your Google Meet link is ready below." : " See you there!"}
            </p>
            {sessionType === "online" && meetingLink && (
              <div className="mb-4 p-4 rounded-lg bg-accent/10 border border-accent/20">
                <div className="flex items-center gap-2 mb-2">
                  <Video className="h-4 w-4 text-primary" />
                  <Label className="text-sm font-medium">Google Meet Link</Label>
                </div>
                <div className="flex items-center gap-2">
                  <div className="flex-1 p-2 rounded-md bg-background border text-sm font-mono truncate">
                    {meetingLink}
                  </div>
                  <Button
                    type="button"
                    variant="outline"
                    size="icon"
                    onClick={() => {
                      navigator.clipboard.writeText(meetingLink)
                      setCopied(true)
                      setTimeout(() => setCopied(false), 2000)
                    }}
                  >
                    {copied ? (
                      <Check className="h-4 w-4 text-green-500" />
                    ) : (
                      <Copy className="h-4 w-4" />
                    )}
                  </Button>
                </div>
                <Button
                  type="button"
                  variant="default"
                  className="w-full mt-3"
                  onClick={() => window.open(meetingLink, "_blank")}
                >
                  <Video className="h-4 w-4 mr-2" />
                  Open Google Meet
                </Button>
              </div>
            )}
            <Button onClick={handleClose} className="w-full">
              Done
            </Button>
          </div>
        )}
      </DialogContent>
    </Dialog>
  )
}
